name: Mirror to Destination

on:
  push:
    branches: [ main ]  # Trigger on pushes to main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Critical for force push to work

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add Destination Remote
        run: |
          git remote add destination "https://adigitalcare:${{ secrets.DESTINATION_PAT }}@github.com/adigitalcare/prachem-chatbot.git"

      - name: Force Push to Destination
        run: |
          git push destination main --force
